name: vinoveritas
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  url_launcher: ^6.1.11
  cupertino_icons: ^1.0.6
  go_router: ^14.1.4
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.3
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  flutter_bloc: ^8.1.6
  get: ^4.6.6
  bloc: ^8.1.4
  meta: ^1.7.0
  provider: ^6.1.2
  get_it: ^7.7.0
  http: ^1.2.1
  tuple: ^2.0.2
  mockito: ^5.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  lints: ^4.0.0
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.11
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  test: ^1.16.0
  mocktail: ^0.2.0
  bloc_test: ^9.0.3

flutter:
  uses-material-design: true

  assets:
    - assets/images/wine.png
    - assets/images/wine2.jpg
    - assets/images/wine3.jpg
    - assets/images/wine4.jpg
    - assets/images/RotweinGlas.png
    - assets/images/WeissweinGlas.png
    - assets/images/RoseweinGlas.png
    - assets/images/RotweinFlasche.png
    - assets/images/RoseweinFlasche.png
    - assets/images/WeissweinFlasche.png
    - assets/images/VinoVeritas-Logo.png
    - assets/images/Edeka.png
    - assets/images/Netto.png
    - assets/images/Rewe.png
    - assets/images/Kaufland.png
    - assets/images/Aldi.png
    - assets/images/Lidl.png
    - assets/images/Penny.png
    - assets/images/Generic_Supermarket.png
