// Mocks generated by Mockito 5.4.4 from annotations
// in vinoveritas/test/src/features/facts_feature/controller/wine_fact_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;
import 'package:vinoveritas/src/model/facts/wine_fact_model.dart'
    as _i2;
import 'package:vinoveritas/src/repository/wine_fact_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeWineFact_0 extends _i1.SmartFake implements _i2.WineFact {
  _FakeWineFact_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [WineFactRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockWineFactRepository extends _i1.Mock
    implements _i3.WineFactRepository {
  MockWineFactRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get apiUrl => (super.noSuchMethod(
        Invocation.getter(#apiUrl),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#apiUrl),
        ),
      ) as String);

  @override
  _i5.Future<_i2.WineFact> fetchWineFact() => (super.noSuchMethod(
        Invocation.method(
          #fetchWineFact,
          [],
        ),
        returnValue: _i5.Future<_i2.WineFact>.value(_FakeWineFact_0(
          this,
          Invocation.method(
            #fetchWineFact,
            [],
          ),
        )),
      ) as _i5.Future<_i2.WineFact>);
}
